#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

set -e

if [ -z "$3" ]; then
    cat <<EOF
Usage: $0 <release-version> <rc-num> <new-development-version-without-SNAPSHOT-suffix>
Example: $0 1.11.0 7 1.12.0
EOF
  exit 1
fi

release_version="$1"
release_tag="apache-parquet-$release_version"
rc_tag="$release_tag-rc$2"
new_development_version="$3-SNAPSHOT"

git tag -am "Release Apache Parquet $release_version" "$release_tag" "$rc_tag"
mvn --batch-mode release:update-versions -DdevelopmentVersion="$new_development_version"
git commit -am 'Prepare for next development iteration'

echo
echo "Verify the release tag and the current development version then push the changes by running: git push --follow-tags"
