package org.apache.parquet;

/**
 * This class is auto-generated by {@link org.apache.parquet.version.VersionGenerator}
 * Do not manually edit!
 */
public class Version {
  public static final String VERSION_NUMBER = "1.8.2-SNAPSHOT";
  public static final String FULL_VERSION = "parquet-mr version 1.8.2-SNAPSHOT (build )";

  public static void main(String[] args) {
    System.out.println(FULL_VERSION);
  }
}
