/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.parquet.column.values.alp;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * Cross-implementation tests: decode C++ reference blobs with the Java decoder.
 *
 * <p>Reference blobs were generated by the C++ Arrow ALP implementation using
 * {@code generate_reference_blobs.cc}. These tests verify that the Java decoder
 * produces bit-identical output for the same compressed bytes.
 */
public class AlpCrossImplTest {

  // ========== Auto-generated reference data from C++ ==========

  // === Float decimal values (16 elements) ===
  private static final float[] FLOAT_DECIMAL_INPUT = {
      Float.intBitsToFloat(0x00000000), Float.intBitsToFloat(0x3DCCCCCD),
      Float.intBitsToFloat(0x3E4CCCCD), Float.intBitsToFloat(0x3E99999A),
      Float.intBitsToFloat(0x3ECCCCCD), Float.intBitsToFloat(0x3F000000),
      Float.intBitsToFloat(0x3F19999A), Float.intBitsToFloat(0x3F333333),
      Float.intBitsToFloat(0x3F4CCCCD), Float.intBitsToFloat(0x3F666667),
      Float.intBitsToFloat(0x3F800000), Float.intBitsToFloat(0x3F8CCCCD),
      Float.intBitsToFloat(0x3F99999A), Float.intBitsToFloat(0x3FA66667),
      Float.intBitsToFloat(0x3FB33333), Float.intBitsToFloat(0x3FC00000)
  };

  // FLOAT_DECIMAL_COMPRESSED (28 bytes)
  private static final byte[] FLOAT_DECIMAL_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x07, (byte)0x06, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x04, (byte)0x10,
      (byte)0x32, (byte)0x54, (byte)0x76, (byte)0x98, (byte)0xBA, (byte)0xDC, (byte)0xFE
  };

  // === Float integer values (16 elements) ===
  private static final float[] FLOAT_INTEGER_INPUT = {
      Float.intBitsToFloat(0x00000000), Float.intBitsToFloat(0x41200000),
      Float.intBitsToFloat(0x41A00000), Float.intBitsToFloat(0x41F00000),
      Float.intBitsToFloat(0x42200000), Float.intBitsToFloat(0x42480000),
      Float.intBitsToFloat(0x42700000), Float.intBitsToFloat(0x428C0000),
      Float.intBitsToFloat(0x42A00000), Float.intBitsToFloat(0x42B40000),
      Float.intBitsToFloat(0x42C80000), Float.intBitsToFloat(0x42DC0000),
      Float.intBitsToFloat(0x42F00000), Float.intBitsToFloat(0x43020000),
      Float.intBitsToFloat(0x430C0000), Float.intBitsToFloat(0x43160000)
  };

  // FLOAT_INTEGER_COMPRESSED (36 bytes)
  private static final byte[] FLOAT_INTEGER_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x07, (byte)0x07, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x08, (byte)0x00,
      (byte)0x0A, (byte)0x14, (byte)0x1E, (byte)0x28, (byte)0x32, (byte)0x3C, (byte)0x46,
      (byte)0x50, (byte)0x5A, (byte)0x64, (byte)0x6E, (byte)0x78, (byte)0x82, (byte)0x8C,
      (byte)0x96
  };

  // === Float with special values (16 elements) ===
  private static final float[] FLOAT_SPECIAL_INPUT = {
      Float.intBitsToFloat(0x00000000), Float.intBitsToFloat(0x3FC00000),
      Float.intBitsToFloat(0x40400000), Float.intBitsToFloat(0x7FC00000),
      Float.intBitsToFloat(0x40C00000), Float.intBitsToFloat(0x40F00000),
      Float.intBitsToFloat(0x41100000), Float.intBitsToFloat(0x7F800000),
      Float.intBitsToFloat(0x41400000), Float.intBitsToFloat(0x41580000),
      Float.intBitsToFloat(0x41700000), Float.intBitsToFloat(0xFF800000),
      Float.intBitsToFloat(0x41900000), Float.intBitsToFloat(0x419C0000),
      Float.intBitsToFloat(0x80000000), Float.intBitsToFloat(0x41B40000)
  };

  // FLOAT_SPECIAL_COMPRESSED (60 bytes)
  private static final byte[] FLOAT_SPECIAL_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x07, (byte)0x06, (byte)0x04,
      (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x08, (byte)0x00,
      (byte)0x0F, (byte)0x1E, (byte)0x00, (byte)0x3C, (byte)0x4B, (byte)0x5A, (byte)0x00,
      (byte)0x78, (byte)0x87, (byte)0x96, (byte)0x00, (byte)0xB4, (byte)0xC3, (byte)0x00,
      (byte)0xE1, (byte)0x03, (byte)0x00, (byte)0x07, (byte)0x00, (byte)0x0B, (byte)0x00,
      (byte)0x0E, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0xC0, (byte)0x7F, (byte)0x00,
      (byte)0x00, (byte)0x80, (byte)0x7F, (byte)0x00, (byte)0x00, (byte)0x80, (byte)0xFF,
      (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x80
  };

  // === Double decimal values (16 elements) ===
  private static final double[] DOUBLE_DECIMAL_INPUT = {
      Double.longBitsToDouble(0x0000000000000000L),
      Double.longBitsToDouble(0x3F847AE147AE147BL),
      Double.longBitsToDouble(0x3F947AE147AE147BL),
      Double.longBitsToDouble(0x3F9EB851EB851EB8L),
      Double.longBitsToDouble(0x3FA47AE147AE147BL),
      Double.longBitsToDouble(0x3FA999999999999AL),
      Double.longBitsToDouble(0x3FAEB851EB851EB8L),
      Double.longBitsToDouble(0x3FB1EB851EB851ECL),
      Double.longBitsToDouble(0x3FB47AE147AE147BL),
      Double.longBitsToDouble(0x3FB70A3D70A3D70AL),
      Double.longBitsToDouble(0x3FB999999999999AL),
      Double.longBitsToDouble(0x3FBC28F5C28F5C29L),
      Double.longBitsToDouble(0x3FBEB851EB851EB8L),
      Double.longBitsToDouble(0x3FC0A3D70A3D70A4L),
      Double.longBitsToDouble(0x3FC1EB851EB851ECL),
      Double.longBitsToDouble(0x3FC3333333333333L)
  };

  // DOUBLE_DECIMAL_COMPRESSED (32 bytes)
  private static final byte[] DOUBLE_DECIMAL_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x0E, (byte)0x0C, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x04, (byte)0x10, (byte)0x32, (byte)0x54, (byte)0x76,
      (byte)0x98, (byte)0xBA, (byte)0xDC, (byte)0xFE
  };

  // === Double integer values (16 elements) ===
  private static final double[] DOUBLE_INTEGER_INPUT = {
      Double.longBitsToDouble(0x0000000000000000L),
      Double.longBitsToDouble(0x4024000000000000L),
      Double.longBitsToDouble(0x4034000000000000L),
      Double.longBitsToDouble(0x403E000000000000L),
      Double.longBitsToDouble(0x4044000000000000L),
      Double.longBitsToDouble(0x4049000000000000L),
      Double.longBitsToDouble(0x404E000000000000L),
      Double.longBitsToDouble(0x4051800000000000L),
      Double.longBitsToDouble(0x4054000000000000L),
      Double.longBitsToDouble(0x4056800000000000L),
      Double.longBitsToDouble(0x4059000000000000L),
      Double.longBitsToDouble(0x405B800000000000L),
      Double.longBitsToDouble(0x405E000000000000L),
      Double.longBitsToDouble(0x4060400000000000L),
      Double.longBitsToDouble(0x4061800000000000L),
      Double.longBitsToDouble(0x4062C00000000000L)
  };

  // DOUBLE_INTEGER_COMPRESSED (40 bytes)
  private static final byte[] DOUBLE_INTEGER_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x10, (byte)0x10, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x08, (byte)0x00, (byte)0x0A, (byte)0x14, (byte)0x1E,
      (byte)0x28, (byte)0x32, (byte)0x3C, (byte)0x46, (byte)0x50, (byte)0x5A, (byte)0x64,
      (byte)0x6E, (byte)0x78, (byte)0x82, (byte)0x8C, (byte)0x96
  };

  // === Float constant (16 elements) ===
  private static final float[] FLOAT_CONSTANT_INPUT = {
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3),
      Float.intBitsToFloat(0x4048F5C3), Float.intBitsToFloat(0x4048F5C3)
  };

  // FLOAT_CONSTANT_COMPRESSED (20 bytes)
  private static final byte[] FLOAT_CONSTANT_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x08, (byte)0x00,
      (byte)0x00, (byte)0x3A, (byte)0x01, (byte)0x00, (byte)0x00, (byte)0x00
  };

  // === Double constant (16 elements) ===
  private static final double[] DOUBLE_CONSTANT_INPUT = {
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL),
      Double.longBitsToDouble(0x40091EB851EB851FL)
  };

  // DOUBLE_CONSTANT_COMPRESSED (24 bytes)
  private static final byte[] DOUBLE_CONSTANT_COMPRESSED = {
      (byte)0x00, (byte)0x00, (byte)0x0A, (byte)0x10, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x04, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x12, (byte)0x10, (byte)0x00,
      (byte)0x00, (byte)0x3A, (byte)0x01, (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00,
      (byte)0x00, (byte)0x00, (byte)0x00
  };

  // ========== Tests: decode C++ blobs, verify output matches input ==========

  @Test
  public void testDecodeFloatDecimal() {
    float[] output = new float[FLOAT_DECIMAL_INPUT.length];
    AlpWrapper.decodeFloats(
        FLOAT_DECIMAL_COMPRESSED, FLOAT_DECIMAL_COMPRESSED.length,
        output, FLOAT_DECIMAL_INPUT.length);
    assertFloatArrayBitEqual(FLOAT_DECIMAL_INPUT, output);
  }

  @Test
  public void testDecodeFloatInteger() {
    float[] output = new float[FLOAT_INTEGER_INPUT.length];
    AlpWrapper.decodeFloats(
        FLOAT_INTEGER_COMPRESSED, FLOAT_INTEGER_COMPRESSED.length,
        output, FLOAT_INTEGER_INPUT.length);
    assertFloatArrayBitEqual(FLOAT_INTEGER_INPUT, output);
  }

  @Test
  public void testDecodeFloatSpecial() {
    float[] output = new float[FLOAT_SPECIAL_INPUT.length];
    AlpWrapper.decodeFloats(
        FLOAT_SPECIAL_COMPRESSED, FLOAT_SPECIAL_COMPRESSED.length,
        output, FLOAT_SPECIAL_INPUT.length);
    assertFloatArrayBitEqual(FLOAT_SPECIAL_INPUT, output);
  }

  @Test
  public void testDecodeDoubleDecimal() {
    double[] output = new double[DOUBLE_DECIMAL_INPUT.length];
    AlpWrapper.decodeDoubles(
        DOUBLE_DECIMAL_COMPRESSED, DOUBLE_DECIMAL_COMPRESSED.length,
        output, DOUBLE_DECIMAL_INPUT.length);
    assertDoubleArrayBitEqual(DOUBLE_DECIMAL_INPUT, output);
  }

  @Test
  public void testDecodeDoubleInteger() {
    double[] output = new double[DOUBLE_INTEGER_INPUT.length];
    AlpWrapper.decodeDoubles(
        DOUBLE_INTEGER_COMPRESSED, DOUBLE_INTEGER_COMPRESSED.length,
        output, DOUBLE_INTEGER_INPUT.length);
    assertDoubleArrayBitEqual(DOUBLE_INTEGER_INPUT, output);
  }

  @Test
  public void testDecodeFloatConstant() {
    float[] output = new float[FLOAT_CONSTANT_INPUT.length];
    AlpWrapper.decodeFloats(
        FLOAT_CONSTANT_COMPRESSED, FLOAT_CONSTANT_COMPRESSED.length,
        output, FLOAT_CONSTANT_INPUT.length);
    assertFloatArrayBitEqual(FLOAT_CONSTANT_INPUT, output);
  }

  @Test
  public void testDecodeDoubleConstant() {
    double[] output = new double[DOUBLE_CONSTANT_INPUT.length];
    AlpWrapper.decodeDoubles(
        DOUBLE_CONSTANT_COMPRESSED, DOUBLE_CONSTANT_COMPRESSED.length,
        output, DOUBLE_CONSTANT_INPUT.length);
    assertDoubleArrayBitEqual(DOUBLE_CONSTANT_INPUT, output);
  }

  // ========== Helpers ==========

  private static void assertFloatArrayBitEqual(float[] expected, float[] actual) {
    assertEquals("array length mismatch", expected.length, actual.length);
    for (int i = 0; i < expected.length; i++) {
      assertEquals(
          "Mismatch at index " + i
              + ": expected " + expected[i] + " (0x"
              + Integer.toHexString(Float.floatToRawIntBits(expected[i]))
              + "), got " + actual[i] + " (0x"
              + Integer.toHexString(Float.floatToRawIntBits(actual[i])) + ")",
          Float.floatToRawIntBits(expected[i]),
          Float.floatToRawIntBits(actual[i]));
    }
  }

  private static void assertDoubleArrayBitEqual(double[] expected, double[] actual) {
    assertEquals("array length mismatch", expected.length, actual.length);
    for (int i = 0; i < expected.length; i++) {
      assertEquals(
          "Mismatch at index " + i
              + ": expected " + expected[i] + " (0x"
              + Long.toHexString(Double.doubleToRawLongBits(expected[i]))
              + "), got " + actual[i] + " (0x"
              + Long.toHexString(Double.doubleToRawLongBits(actual[i])) + ")",
          Double.doubleToRawLongBits(expected[i]),
          Double.doubleToRawLongBits(actual[i]));
    }
  }
}
