name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '1.8', '11' ]
        codes: [ 'uncompressed,brotli', 'gzip,snappy' ]
    name: Build Parquet with JDK ${{ matrix.java }} and ${{ matrix.codes }}

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: before_install
        run: |
          bash dev/travis-before_install.sh
      - name: install
        run: |
          mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true -Djava.version=${{ matrix.java }}
      - name: verify
        env:
          HADOOP_PROFILE: default
          TEST_CODECS: ${{ matrix.codes }}
        run: |
          mvn verify --batch-mode javadoc:javadoc -Ptravis,$HADOOP_PROFILE
